# Generated by Django 5.2.7 on 2025-10-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalparks',
            name='activity',
            field=models.ManyToManyField(to='my_app.activity'),
        ),
    ]
